Bid/urls.py
from django.urls import path

from .views import BidCreateView, BidDetailView, MyBidsListView,BidUpdateView,BidDeleteView

app_name = "bids"
urlpatterns = [
    path("bid-details/<slug>/", BidDetailView.as_view(), name="bid-details"),
    path("add-bid/<slug>", BidCreateView.as_view(), name="add-bids"),
    path("my-bids/", MyBidsListView.as_view(), name="my-bids"),
    path("update-bid/<slug>", BidUpdateView.as_view(), name="update-bids"),
    path("delete-bids/<slug>/", BidDeleteView.as_view(), name="delete-bids"),
]

Ukulima/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lands/", include("Shamba.urls")),
    path("tools/", include("Tools.urls")),
    path("services/", include("Services.urls")),
    path("produce/", include("Produce.urls")),
    path("profile/", include("Profile.urls")),
    path("accounts/", include("allauth.urls")),
    path("carts/", include("Cart.urls")),
    path("bids/", include("Bid.urls")),
    path("", include('Pages.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bid/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from django_extensions.db.fields import AutoSlugField
import uuid
from ckeditor.fields import RichTextField
from django.utils.translation import gettext as _
from Produce.models import Produce
# Create your models here.
class Bid(models.Model):
    """Model definition for Bid."""

    # TODO: Define fields here
    uuid =models.UUIDField(primary_key=True,editable=False,default=uuid.uuid4)
    user =models.ForeignKey(User, verbose_name=_(""), on_delete=models.CASCADE)
    produce = models.ForeignKey(Produce, verbose_name=_(""), on_delete=models.CASCADE)
    charge =models.IntegerField(_("Charge"))
    reasons =RichTextField(_("Reasons For you charge"))
    services =RichTextField(_("Other secondary Services "),blank=True, null=True)
    status = models.CharField(_(""),default="PENDING", max_length=50)
    approved_cancelled_time =models.DateTimeField(_(""),blank=True, null=True)
    created = models.DateTimeField( auto_now=False, auto_now_add=True)

    class Meta:
        """Meta definition for Bid."""

        verbose_name = 'Bid'
        verbose_name_plural = 'Bids'

    def __str__(self):
        """Unicode representation of Bid."""
        return f"Produce {self.produce.title}, has a bid of {self.charge}"

    # def save(self):
    #     """Save method for Bid."""
    #     pass

    def get_absolute_url(self):
        """Return absolute url for Bid."""
        return reverse ('bids:bid-details', kwargs={'slug': self.uuid})

    # TODO: Define custom methods here

Bid/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from .models import Bid


class EditBidForm(forms.ModelForm):
    """Form definition for Bid."""

    class Meta:
        """Meta definition for Bidform."""

        model = Bid
        fields = ("charge", "reasons", "services")
        labels = {
            "charge": "Charge",
            "reasons": "Reasons For That Price",
            "services": "Any secondary services",
        }
        widgets ={
            "charge":forms.NumberInput(attrs={"class":"form-control charge","required":True}),
            "reasons":CKEditorWidget(attrs={"class":"form-control reasons","required":True}),
            "services":CKEditorWidget(attrs={"class":"form-control"})
        }
from ckeditor.widgets import CKEditorWidget
from django import forms

from .models import Bid


class BidForm(forms.ModelForm):
    """Form definition for Bid."""

    class Meta:
        """Meta definition for Bidform."""

        model = Bid
        fields = ("charge", "reasons", "services")
        labels = {
            "charge": "Charge",
            "reasons": "Reasons For That Price",
            "services": "Any secondary services",
        }
        widgets ={
            "charge":forms.NumberInput(attrs={"class":"form-control charge","required":True}),
            "reasons":CKEditorWidget(attrs={"class":"form-control reasons","required":True}),
            "services":CKEditorWidget(attrs={"class":"form-control"})
        }

Bid/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from .forms import BidForm,EditBidForm
from django.views.generic import CreateView,ListView,DetailView,UpdateView,DeleteView
from .models import Bid
from Produce.models import Produce
from django.contrib.auth.models import User
from django.contrib import messages
# Create your views here.


class BidCreateView(CreateView):
    model = Bid
    form_class = BidForm
    template_name = "bids/add-bid.html"
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        bid = form.save(commit=False)
        bid.user = self.request.user
        slug = self.kwargs["slug"]
        bid.produce =Produce.objects.get(slug=slug)
        bid.save()
        return super(BidCreateView,self).form_valid(form)
    def get_success_url(self) -> str:
        return reverse_lazy('produce')

class MyBidsListView(ListView):
    model = Bid
    template_name = "bids/my-bids.html"
    context_object_name ='bids'
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('user','produce').filter(user = self.request.user)
        return  queryset
    

class BidDetailView(DetailView):
    model = Bid
    template_name = "bids/bid-details.html"
    slug_field = "uuid"
    slug_url_kwarg = "slug"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bid"] = self.get_object()
        return context
    

class BidUpdateView(UpdateView):
    model = Bid
    template_name = "bids/update-bid.html"
    form_class = EditBidForm
    success_url ="bids:my-bids"
    slug_field = "uuid"
    slug_url_kwarg = "slug"
    success_url = reverse_lazy("bids:my-bids")
    
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            messages.error(request, "You dont have permission to edit this ")
            return redirect(reverse("bids:bid-details", args=[obj.uuid]))

        return super().dispatch(request, *args, **kwargs)



class BidDeleteView(DeleteView):
    model = Bid
    template_name = "bids/delete-bid.html"
    success_url ="bids:my-bids"
    slug_field = "uuid"
    slug_url_kwarg = "slug"
    success_url = reverse_lazy("bids:my-bids")
    
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user != self.request.user:
            messages.error(request, "You dont have permission to edit this ")
            return redirect(reverse("bids:bid-details", args=[obj.uuid]))

        return super().dispatch(request, *args, **kwargs)

templates/bids/add-bid.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Tools{% endblock title %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
<input type="submit" value="{% translate "submit" %}"/>
</form>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

templates/bids/bid-details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  bids 
{% endblock title %}
    
{% block content %}
<H1>i am services </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{bid.get_absolute_url}}">{{bid.charge}}</a> </h5>        
        <p class="card-text"><small class="text-muted">{{bid.created}}</small></p>
        <p class="card-text">Reasons: {{bid.reasons}}</p>
        <p class="card-text">Services:{{bid.services}}</p>
        <p class="card-text">Status:{{bid.status}}</p>
        <a href="{% url 'bids:update-bids' bid.uuid %}" class="btn btn-danger">Update</a>
        <a href="{% url 'bids:delete-bids' bid.uuid %}" class="btn btn-primary">Delete</a>
      </div>
    </div>
  </div>
</div>
      
        </div>
       
    </div>
</div>

{% endblock content %}

templates/bids/delete-bid.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Tools{% endblock title %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
<input type="submit" value="{% translate "submit" %}"/>
</form>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

templates/bids/my-bids.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  bids 
{% endblock title %}
    
{% block content %}
<H1>i am services </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for bid in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{bid.get_absolute_url}}">{{bid.charge}}</a> </h5>        
        <p class="card-text"><small class="text-muted">{{bid.created}}</small></p>
        <p class="card-text">Reasons: {{bid.reasons}}</p>
        <p class="card-text">Services:{{bid.services}}</p>
        <p class="card-text">Status:{{bid.status}}</p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No bids found </p>
        {% endfor %}

        </div>
       
    </div>
</div>

{% endblock content %}

templates/bids/update-bid.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Tools{% endblock title %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
<input type="submit" value="{% translate "submit" %}"/>
</form>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}