Bid/urls.py
from django.urls import path

from .views import BidCreateView, BidDetailView, MyBidsListView,BidUpdateView,BidDeleteView

app_name = "bids"
urlpatterns = [
    path("bid-details/<slug>/", BidDetailView.as_view(), name="bid-details"),
    path("add-bid/<slug>", BidCreateView.as_view(), name="add-bids"),
    path("my-bids/", MyBidsListView.as_view(), name="my-bids"),
    path("update-bid/<slug>", BidUpdateView.as_view(), name="update-bids"),
    path("delete-bids/<slug>/", BidDeleteView.as_view(), name="delete-bids"),
]

Ukulima/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lands/", include("Shamba.urls")),
    path("tools/", include("Tools.urls")),
    path("services/", include("Services.urls")),
    path("produce/", include("Produce.urls")),
    path("profile/", include("Profile.urls")),
    path("accounts/", include("allauth.urls")),
    path("carts/", include("Cart.urls")),
    path("bids/", include("Bid.urls")),
    path("", include('Pages.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
 <!-- Start Footer Area -->
    <footer class="footer section">
        <!-- Start Footer Top -->
        <div class="footer-top">
            <div class="container">
                <div class="inner-content">
                    <div class="row">
                        <div class="col-lg-4 col-md-6 col-12">
                            <!-- Single Widget -->
                            <div class="single-footer f-about">
                                <div class="logo">
                                    <a href="index-2.html">
                                        <img src="assets/images/logo/logo.svg" alt="#">
                                    </a>
                                </div>
                                <p>Making the world a better place through constructing elegant hierarchies.</p>
                                <p class="copyright-text"><span>© 2023 Blink.</span>Designed and Developed by <a
                                        href="https://graygrids.com/" rel="nofollow" target="_blank">GrayGrids</a>
                                </p>
                            </div>
                            <!-- End Single Widget -->
                        </div>
                        <div class="col-lg-2 col-md-6 col-12">
                            <!-- Single Widget -->
                            <div class="single-footer f-link">
                                <h3>Solutions</h3>
                                <ul>
                                    <li><a href="javascript:void(0)">Marketing</a></li>
                                    <li><a href="javascript:void(0)">Analytics</a></li>
                                    <li><a href="javascript:void(0)">Commerce</a></li>
                                    <li><a href="javascript:void(0)">Insights</a></li>
                                </ul>
                            </div>
                            <!-- End Single Widget -->
                        </div>
                        <div class="col-lg-2 col-md-6 col-12">
                            <!-- Single Widget -->
                            <div class="single-footer f-link">
                                <h3>Support</h3>
                                <ul>
                                    <li><a href="javascript:void(0)">Pricing</a></li>
                                    <li><a href="javascript:void(0)">Documentation</a></li>
                                    <li><a href="javascript:void(0)">Guides</a></li>
                                    <li><a href="javascript:void(0)">API Status</a></li>
                                </ul>
                            </div>
                            <!-- End Single Widget -->
                        </div>
                        <div class="col-lg-4 col-md-6 col-12">
                            <!-- Single Widget -->
                            <div class="single-footer newsletter">
                                <h3>Subscribe</h3>
                                <p>Subscribe to our newsletter for the latest updates</p>
                                <form action="#" method="get" target="_blank" class="newsletter-form">
                                    <input name="EMAIL" placeholder="Email address" required="required" type="email">
                                    <div class="button">
                                        <button class="sub-btn"><i class="lni lni-envelope"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                            <!-- End Single Widget -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ End Footer Top -->
    </footer>
    <!--/ End Footer Area -->

templates/includes/header.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'land' %}">Lands</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'add-land' %}">Addland</a>
        </li>
         <li class="nav-item">
          {% comment %} <a class="nav-link" href="{% url 'my-bookmarks' user.username %}">My-Bookmarks</a> {% endcomment %}
        </li>
        {% comment %} for lands  {% endcomment %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'my-lands' %}">My-lands</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bids:my-bids' %}">My-bids</a>
        </li> 
        
        <li class="nav-item">
          {% comment %} <a class="nav-link" href="{% url 'my-bookmarks' user.username %}">Land My-Bookmarks</a> {% endcomment %}
        </li>
        {% comment %} for tools  {% endcomment %}
        </li> <li class="nav-item">
          {% comment %} <a class="nav-link" href="{% url 'my-tool-bookmarks' user.username %}">Tools My-Bookmarks</a> {% endcomment %}
        </li>
        </li> <li class="nav-item">
          <a class="nav-link" href="{% url 'my-tools' %}">My Tools</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link " href="{% url 'add-tools' %}">Add tool</a>
        </li> {% endcomment %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Tools
          </a>
          <ul class="dropdown-menu">
            
            
            
              <li><a class="dropdown-item" href="{% url 'tools' %}">Tools</a></li>
              <li><a class="dropdown-item" href="{% url 'add-tools' %}">Add Tools</a></li>
            
              
            {% comment %} <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li> {% endcomment %}
            <li><a class="dropdown-item" href="#"></a></li>
            <li><hr class="dropdown-divider"></li>
           
          </ul>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Produce
          </a>
          <ul class="dropdown-menu">
            
            
            
              <li><a class="dropdown-item" href="{% url 'produce' %}">Produces</a></li>
              <li><a class="dropdown-item" href="{% url 'add-produce' %}">Add Tools</a></li>
              <li><a class="dropdown-item" href="{% url 'produce-bookmarks' %}">Produces Bookmark</a></li>
               <li><a class="dropdown-item" href="{% url 'my-produce' %}">My Produces</a></li>
              
            
              
            {% comment %} <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li> {% endcomment %}
            <li><a class="dropdown-item" href="#"></a></li>
            <li><hr class="dropdown-divider"></li>
           
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <ul class="dropdown-menu">
            
            
            {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
            {% endif %}
              
            
              
            
              
            {% comment %} <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li> {% endcomment %}
            <li><a class="dropdown-item" href="#"></a></li>
            <li><hr class="dropdown-divider"></li>
           
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <ul class="dropdown-menu">
            
            
{% comment %}             
              <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
             {% endcomment %}
              
            {% comment %} <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li> {% endcomment %}
            <li><a class="dropdown-item" href="#"></a></li>
            <li><hr class="dropdown-divider"></li>
           
          </ul>
        </li>
        {% if user.is_authenticated %}
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <ul class="dropdown-menu">
            
            
            
              {% comment %} <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
             {% endcomment %}
              
            {% comment %} <li><a class="dropdown-item" href="{% url 'profile' user.profile.slug %}">Profile</a></li> {% endcomment %}
            <li><a class="dropdown-item" href="#"></a></li>
            <li><hr class="dropdown-divider"></li>
           
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">Login</a>
        </li>
        {% endif %}

        
        {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart' %}">Cart</a>
        </li> 
        {% endif %}
          
        

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% comment %} hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh {% endcomment %}
 <!-- Start Header Area -->
    {% comment %} <header class="header navbar-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="nav-inner">
                        <!-- Start Navbar -->
                        <nav class="navbar navbar-expand-lg">
                            <a class="navbar-brand" href="index-2.html">
                                <img src="assets/images/logo/logo.svg" alt="Logo">
                            </a>
                            <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                                <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                                <ul id="nav" class="navbar-nav ms-auto">
                                    
                                    <li class="nav-item active">
                                        <a href="contact.html" aria-label="Toggle navigation">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dd-menu collapsed" href="javascript:void(0)" data-bs-toggle="collapse"
                                            data-bs-target="#submenu-1-2" aria-controls="navbarSupportedContent"
                                            aria-expanded="false" aria-label="Toggle navigation">Pages</a>
                                        <ul class="sub-menu collapse" id="submenu-1-2">
                                            <li class="nav-item"><a href="about-us.html">About Us</a></li>
                                            <li class="nav-item"><a href="pricing.html">Our Pricing</a></li>
                                            <li class="nav-item"><a href="services.html">Our Services</a></li>
                                            <li class="nav-item"><a href="signin.html">Sign In</a></li>
                                            <li class="nav-item"><a href="signup.html">Sign Up</a></li>
                                            <li class="nav-item"><a href="reset-password.html">Reset Password</a></li>
                                            <li class="nav-item"><a href="mail-success.html">Mail Success</a></li>
                                            <li class="nav-item"><a href="404.html">404 Error</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a href="services.html" aria-label="Toggle navigation">Services</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dd-menu collapsed" href="javascript:void(0)" data-bs-toggle="collapse"
                                            data-bs-target="#submenu-1-3" aria-controls="navbarSupportedContent"
                                            aria-expanded="false" aria-label="Toggle navigation">Blog</a>
                                        <ul class="sub-menu collapse" id="submenu-1-3">
                                            <li class="nav-item"><a href="blog-grid.html">Blog Grid</a>
                                            </li>
                                            <li class="nav-item"><a href="blog-single.html">Blog Single</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a href="contact.html" aria-label="Toggle navigation">Contact</a>
                                    </li>
                                </ul>
                            </div> <!-- navbar collapse -->
                            <div class="button">
                                <a href="signin.html" class="signin">Sign In</a>
                                <a href="signup.html" class="signup">Sign Up</a>
                            </div>
                        </nav>
                        <!-- End Navbar -->
                    </div>
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </header>
    <!-- End Header Area --> {% endcomment %}