Bid/urls.py
from django.urls import path

from .views import BidCreateView, BidDetailView, MyBidsListView,BidUpdateView,BidDeleteView

app_name = "bids"
urlpatterns = [
    path("bid-details/<slug>/", BidDetailView.as_view(), name="bid-details"),
    path("add-bid/<slug>", BidCreateView.as_view(), name="add-bids"),
    path("my-bids/", MyBidsListView.as_view(), name="my-bids"),
    path("update-bid/<slug>", BidUpdateView.as_view(), name="update-bids"),
    path("delete-bids/<slug>/", BidDeleteView.as_view(), name="delete-bids"),
]

Ukulima/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lands/", include("Shamba.urls")),
    path("tools/", include("Tools.urls")),
    path("services/", include("Services.urls")),
    path("produce/", include("Produce.urls")),
    path("profile/", include("Profile.urls")),
    path("accounts/", include("allauth.urls")),
    path("carts/", include("Cart.urls")),
    path("bids/", include("Bid.urls")),
    path("", include('Pages.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tools/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from .models import Category, Tag, Tool, ToolImage

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result
    
    
class ToolForm(forms.ModelForm):
    """Form definition for Tool."""

    tags = forms.ModelMultipleChoiceField(
        label="Tags",
        widget=forms.SelectMultiple(
            attrs={
                "required": True,
                "class": "form-control tags form-select",
                "id": "tools_tag",
            }
        ),
        queryset=Tag.objects.all()
    )
    description = forms.CharField(
        label="Description",
        widget=CKEditorWidget(
            attrs={"required": True, "class": "form-control description"}
        ),
    )
    images = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={
        'required': False,
        'class': 'form-control images',
        # 'multiple': True
    }))
    # images=MultipleFileField()

    class Meta:
        """Meta definition for Toolform."""

        model = Tool
        labels = {
            "title":'Title',
            "category":'Category',           
            "price":'Price',
            "period":'Period',
            "county":'County',
            "sub_county":'Sub County',
            "location":'Location',
            "village":'Village',
            'inventory':'Available Units'
            
        }
        fields = (
            "title",
            "category",
            "tags",
            "price",
            "period",
            "county",
            "sub_county",
            "location",
            "sub_location",
            "village",
            "description",
            'inventory',
        )
        widget ={
            "title": forms.TextInput(attrs={'class': 'control-form title', 'required': True}),
            "category": forms.Select(attrs={'class': 'control-select category', 'required': True}),
            "price":forms.TextInput(attrs={'class':"form-control price",'required':True}),
            "period": forms.Select(attrs={'class': 'control-select period', 'required': True}),
            "inventory":forms.TextInput(attrs={'class':"form-control inventory",'required':True}),
            "county": forms.Select(attrs={'class': 'control-select county', 'required': True}),
            "sub_county": forms.Select(attrs={'class': 'control-select sub_county', 'required': True}),
            "location": forms.Select(attrs={'class': 'control-select location', 'required': True}),
            "location": forms.TextInput(attrs={'class': 'control-form location', 'required': True}),
            "village": forms.TextInput(attrs={'class': 'control-form village', 'required': True}),
        }


class ToolUpdateForm(forms.ModelForm):
    """Form definition for Tool."""

    tags = forms.ModelMultipleChoiceField(
        label="Tags",
        widget=forms.SelectMultiple(
            attrs={
                "required": True,
                "class": "form-control tags form-select",
                "id": "tools_tag",
            }
        ),
        queryset=Tag.objects.all()
    )
    description = forms.CharField(
        label="Description",
        widget=CKEditorWidget(
            attrs={"required": True, "class": "form-control description"}
        ),
    )
    # images = forms.ImageField(
    #     # required=True,
    #     widget=forms.ClearableFileInput(
    #         attrs={ "required": True, "class": "form-control image",}
    #     ),
    # )

    class Meta:
        """Meta definition for Toolform."""

        model = Tool
        labels = {
            "title":'Title',
            "category":'Category',           
            "price":'Price',
            "period":'Period',
            "county":'County',
            "sub_county":'Sub County',
            "location":'Location',
            "village":'Village',
             'inventory':'Available Units'
            
        }
        fields = (
            "title",
            "category",
            "tags",
            "price",
            "period",
            'inventory',
            "county",
            "sub_county",
            "location",
            "village",
            "description",
        )
        widget ={
            "title": forms.TextInput(attrs={'class': 'control-form title', 'required': True}),
            "category": forms.Select(attrs={'class': 'control-select category', 'required': True}),
            "price":forms.TextInput(attrs={'class':"form-control price",'required':True}),
            "period": forms.Select(attrs={'class': 'control-select period', 'required': True}),
            "county": forms.Select(attrs={'class': 'control-select county', 'required': True}),
            "inventory":forms.TextInput(attrs={'class':"form-control inventory",'required':True}),
            "sub_county": forms.Select(attrs={'class': 'control-select sub_county', 'required': True}),
            "location": forms.Select(attrs={'class': 'control-select location', 'required': True}),
            "location": forms.TextInput(attrs={'class': 'control-form location', 'required': True}),
            "village": forms.TextInput(attrs={'class': 'control-form village', 'required': True}),
        }

templates/lands/add-coordinates.html
{% extends 'base.html' %}
{% block title %}Add Lands Coordinates{% endblock title %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% comment %} {% load i18n %} {% endcomment %}
{% load leaflet_tags %}

{% block head %}
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
 <form action="" method="POST">
    {% comment %} {% csrf_token %} {% endcomment %}
     {{ form }}
     <button type="submit">submit</button>
 </form>
  <script>
   map.on('map:loadfield', function (e) {
    ...
    // Customize map for field
    console.log(e.field, e.fieldid);
    ...
});
</script>

{% comment %} {% leaflet_map "yourmap" callback="window.map_init_basic" %} {% endcomment %}
        </div>
    </div>
</div>
{% comment %} <script>
    var map = L.map('map').setView([51.505, -0.09], 13);
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '© OpenStreetMap'
}).addTo(map);
</script> {% endcomment %}
<script>
function map_init(map, options) {
    console.log('Map initialization function called');
    // Customize your map initialization here
}
</script>

{% endblock %}

templates/lands/add-land.html
{% extends 'base.html' %}
{% block title %}Add Lands{% endblock title %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form|crispy }}
    {% endfor %}
{% else %}
    {{ wizard.form|crispy }}
{% endif %}
</table>
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% translate "first step" %}</button>
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% translate "prev step" %}</button>
{% endif %}
<input type="submit" value="{% translate "submit" %}"/>
</form>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script>
   $("#id_tags").select2(); 
</script>
{% endblock %}

templates/lands/bookmarks.html
{% extends 'base.html' %}

{% block title %}
    Land Bookmarks
{% endblock title %}
    
{% block content %}
<H1>i am lands </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{land.get_absolute_url}}">{{land.land_id}}</a> </h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        <div class="col-md-4">
            <H1>i am sidebar</H1>
        </div>
    </div>
</div>

{% endblock content %}

templates/lands/land-category.html
{% extends 'base.html' %}

{% block title %}
     Lands by category
{% endblock title %}
    
{% block content %}
<H1>i am lands </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{land.get_absolute_url}}">{{land.land_id}}</a> </h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        <div class="col-md-4">
            <H1>i am sidebar</H1>
        </div>
    </div>
</div>

{% endblock content %}

templates/lands/land-delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Delete Land{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <form action="" method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/lands/land-detail.html
{% extends 'base.html' %}

{% block title %}
    Lands Details
{% endblock title %}
    
{% block content %}
    <h1> iam details </h1>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
<div class="card">
  <div class="card-body">
    {% comment %} {% for image in land.land_images.all %}
    <img src="{{image.images.url}}" alt="ooo">
    {% endfor %} {% endcomment %}
    <div>
                                            <ul id="lightSlider">
                                          {% for image in land.land_images.all %}
                                          <li data-thumb="{{image.images.url}}">
                                            <a href="{{image.images.url}}" data-fancybox="gallery">
                                          <img src="{{image.images.url}}" alt="..." class="img-fluid">
                                          </a>
		        </li>
                                          {% endfor %}

  
                                            </ul>
                                            
                                        </div>
    <h5 class="card-title">Card title</h5>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text">Owner: <a href="{% url 'users-lands' land.owner.username %}">{{land.owner}}</a>  </p>
    <p class="card-text">Land ID: {{land.land_id}} </p>
    <p class="card-text">Shamba Id{{land.shamba_id}} </p>
    <p class="card-text"> Locaation: {{land.location}}</p>
    <p class="card-text">Size :{{land.size}} </p>
    <p class="card-text"> <a href="{% url 'land-category' land.category.slug %}">{{land.category}}</a> </p>
    <p class="card-text">Climate :{{land.climate}} </p>
    <p class="card-text">Previous Farming:{{land.previous_farming}} </p>
    <p class="card-text">Water source:{{land.water_source}} </p>
    <p class="card-text">Electricity source :{{land.electricity_source}} </p>
    <p class="card-text"> Period lease{{land.period_lease }}</p>
    <p class="card-text">Charge: {{land.charge}}</p>
    <p class="card-text">Existing Infreacture: {{land.existing_infrastructure}}</p>
    <p class="card-text">Recommend Farmin{{land.recommended_farming}} </p>
    <p class="card-text"> Ceated: {{land.created}}</p>

  </div>
  <img src="..." class="card-img-bottom" alt="...">
</div>
<a href="{% url 'land-update' land.slug %}" class="btn btn-primary">Update land </a>
<a href="{% url 'land-delete' land.slug %}" class="btn btn-danger">Delete land</a>
<a href="{% url 'bookmark' land.slug %}" class="btn btn-secondary">Bookmark land</a>
<a href="{% url 'add-coordinates' land.slug %}" class="btn btn-success">Add Coordinates</a>
<a href="{% url 'add-cart' content_type_id=content_type.id object_id=land.id %}" class="btn btn-success">Add to Cart</a>
        </div>
        <div class="col-md-4">
<h1>sidebar</h1>
{% for similar_land in similar_lands %}
<p>title: {{similar_land.title}} </p>
<p>category : {{similar_land.category}}</p>
{% empty %}
<p>no similar land</p>
{% endfor %}
        </div>
      </div>
    </div>
{% endblock content %}
    

templates/lands/land-filters.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Lands
{% endblock title %}
    
{% block content %}
<H1>i am lands </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in lands %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{land.get_absolute_url}}">{{land.title}}</a> </h5>
        <p class="card-text">Size : <small class="text-muted">{{land.size}} {{land.size_units}}</small></p>
         <p class="card-text">Location : <small class="text-muted">{{land.county}} {{land.sub_county}} {{land.location}} {{land.sub_location}} {{land.village}}</small></p>
         <p class="card-text">Charge : <small class="text-muted">ksh {{land.charge}} for {{land.period_lease}}</small></p>
        <p class="card-text"><small class="text-muted">{{land.created}}</small></p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        <div class="col-md-4">
            <H1>i am sidebar</H1>
            <form action="{% url 'land-filter' %}" method="get">
              {% csrf_token %}
              {{filter.form|crispy}}
              <button type="submit">Filter</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/lands/land-tags.html
{% extends 'base.html' %}

{% block title %}
     Lands by category
{% endblock title %}
    
{% block content %}
<H1>i am lands </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{land.get_absolute_url}}">{{land.land_id}}</a> </h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        <div class="col-md-4">
            <H1>i am sidebar</H1>
        </div>
    </div>
</div>

{% endblock content %}

templates/lands/land-update.html
{% extends 'base.html' %}
{% block title %}Update Land{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container"><div class="row"> 
        <div class="col-md-8">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-primary" type="submit">SUbmit</button>
            </form>
        </div>
    </div> </div>
{% endblock content %}
    

templates/lands/lands.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Lands
{% endblock title %}
    
{% block content %}
<!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Blog Grid Sidebar</h1>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-12">
                    <ul class="breadcrumb-nav">
                        <li><a href="index-2.html">Home</a></li>
                        <li>Blog Grid Sidebar</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->
<!-- Start Blog Singel Area -->
    <section class="section land-grid-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-12 col-12">
                    <div class="row">
                      {% for land in object_list %}
                        <div class="col-lg-6 col-md-6 col-12">
                            <!-- Start Single land Grid -->
                            <div class="single-land-grid">
                                <div class="land-img">
                                    <a href="land-single.html">
                                      {% for image in land.land_images.all %}
                                        <img src="{{image.images.url}}" alt="{{land.title | truncatechars:5}}">
                                      {% endfor %}
                                    </a>
                                </div>
                                <div class="land-content">
                                    <a class="category" href="javascript:void(0)">{{land.category}}</a>
                                    
                                    <h4>
                                        <a href="{{land.get_absolute_url}}">{{land.title}}</a>
                                    </h4>
                                    <p><i class="lni lni-map-marker"></i> {{land.county}}, {{land.sub_county}}</p>
                                    <p>Size : {{land.size}} {{land.size_units}}</p>
                                    <p>ksh {{land.charge}} for {{land.period_lease}}</p>
                                     
         
                                      
                                    
                                </div>
                            </div>
                            
                        </div>
                        {% empty %}
                         <div class="col-lg-6 col-md-6 col-12">
                            
                            <div class="single-land-grid">
                                 <p>No lands found</p>                              
                            </div>
                            <!-- End Single Blog Grid -->
                        </div>

                      {% endfor %}
                        
                    </div>
                    <!-- Pagination -->
                    <div class="pagination left">
                        <ul class="pagination-list">
                            <li><a href="javascript:void(0)">Prev</a></li>
                            <li class="active"><a href="javascript:void(0)">2</a></li>
                            <li><a href="javascript:void(0)">3</a></li>
                            <li><a href="javascript:void(0)">4</a></li>
                            <li><a href="javascript:void(0)">Next</a></li>
                        </ul>
                    </div>
                    <!--/ End Pagination -->
                </div>
                <aside class="col-lg-4 col-md-12 col-12">
                    <div class="sidebar">
                        
                        <!-- Start Single Widget -->
                        <div class="widget popular-feeds">
                            <h5 class="widget-title">Popular Feeds</h5>
                            <div class="popular-feed-loop">
                                <form action="{% url 'land-filter' %}" method="get">
              {% csrf_token %}
              {{filter.form|crispy}}
              <button type="submit">Filter</button>
            </form>
                            </div>
                        </div>
                        <!-- End Single Widget -->
                        <!-- Start Single Widget -->
                        <div class="widget categories-widget">
                            <h5 class="widget-title">Categories</h5>
                            <ul class="custom">
                                {% for category in categories %}                        
                                
                                <li>
                                    <a href="{% url 'land-category' category.slug %}">{{category.type}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- End Single Widget -->
                        <!-- Start Single Widget -->
                        <div class="widget popular-tag-widget">
                            <h5 class="widget-title">Tags</h5>
                            <div class="tags">
                                {% for tag in popular_tags %} 
                                   <a href="{% url 'land-tag' tag.slug %}">{{tag.num_lands}}  {{tag.name}}</a>
                                {% endfor %}
                               
                            </div>
                        </div>
                        <!-- End Single Widget -->
                    </div>
                </aside>
            </div>
        </div>
    </section>
    <!-- End Blog Grid -->

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in object_list %}
           
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        
    </div>
</div>



{% endblock content %}

templates/lands/my-lands.html
{% extends 'base.html' %}

{% block title %}
    My Lands
{% endblock title %}
    
{% block content %}
<H1>i am lands </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{land.get_absolute_url}}">{{land.land_id}}</a> </h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        <div class="col-md-4">
            <H1>i am sidebar</H1>
        </div>
    </div>
</div>

{% endblock content %}

templates/lands/user-lands.html
{% extends 'base.html' %}

{% block title %}
    user Lands
{% endblock title %}
    
{% block content %}
<H1>i am lands </H1>

<div class="container"> 
    <div class="row">
        <div class="col-md-8">
            
        {% for land in object_list %}
            <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><a href="{{land.get_absolute_url}}">{{land.land_id}}</a> </h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
        {% empty %}
        <p>No lands found </p>
        {% endfor %}

        </div>
        <div class="col-md-4">
            <H1>i am sidebar</H1>
        </div>
    </div>
</div>

{% endblock content %}